config/routes.rb
Rails.application.routes.draw do
  root "pokemons#index"
  resources :pokemons, only: [:new, :create]
  resource :session, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authenticate
    redirect_to new_session_path unless signed_in?
  end

  def signed_in?
    session[:current_email].present?
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :authenticate

  def index
    @pokemons = Pokemon.where(email: session[:current_email])
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    pokemon = Pokemon.new pokemon_params
    pokemon.email = session[:current_email]
    pokemon.save
    redirect_to root_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:current_email] = params[:session][:email]
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1>My Pokemons</h1>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h2>Let Me Show You Them</h2>

<%= link_to "Add a new Pokemon", new_pokemon_path %>

<ul class="pokemons">
  <% @pokemons.each do |pokemon| %>
    <li><%= pokemon.name %></li>
  <% end %>
</ul>

app/views/pokemons/new.html.erb
<%= form_for @pokemon do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit "Add Pokemon" %>
<% end %>